# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_form.ui'
#
# Created: Thu Apr 06 00:04:32 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(456, 56)
        Form.setMinimumSize(QtCore.QSize(0, 55))
        Form.setMaximumSize(QtCore.QSize(16777215, 56))
        Form.setAutoFillBackground(True)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 42))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(38, 38))
        self.label.setMaximumSize(QtCore.QSize(38, 38))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/work_file.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(277, 34, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.statusAction = QtGui.QStackedWidget(self.frame)
        self.statusAction.setMinimumSize(QtCore.QSize(38, 38))
        self.statusAction.setMaximumSize(QtCore.QSize(38, 38))
        self.statusAction.setObjectName("statusAction")
        self.checkbox_page = QtGui.QWidget()
        self.checkbox_page.setObjectName("checkbox_page")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.checkbox_page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtGui.QCheckBox(self.checkbox_page)
        self.checkBox.setMinimumSize(QtCore.QSize(25, 25))
        self.checkBox.setMaximumSize(QtCore.QSize(25, 25))
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(25, 25))
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.statusAction.addWidget(self.checkbox_page)
        self.success_page = QtGui.QWidget()
        self.success_page.setObjectName("success_page")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.success_page)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.success_label = QtGui.QLabel(self.success_page)
        self.success_label.setMinimumSize(QtCore.QSize(24, 24))
        self.success_label.setMaximumSize(QtCore.QSize(24, 24))
        self.success_label.setText("")
        self.success_label.setPixmap(QtGui.QPixmap(":/img/success_item.png"))
        self.success_label.setScaledContents(True)
        self.success_label.setObjectName("success_label")
        self.horizontalLayout_4.addWidget(self.success_label)
        self.statusAction.addWidget(self.success_page)
        self.failure_page = QtGui.QWidget()
        self.failure_page.setObjectName("failure_page")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.failure_page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_traceback = QtGui.QPushButton(self.failure_page)
        self.button_traceback.setMinimumSize(QtCore.QSize(24, 24))
        self.button_traceback.setMaximumSize(QtCore.QSize(24, 24))
        self.button_traceback.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/failure_item.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_traceback.setIcon(icon)
        self.button_traceback.setIconSize(QtCore.QSize(24, 24))
        self.button_traceback.setObjectName("button_traceback")
        self.horizontalLayout_5.addWidget(self.button_traceback)
        self.statusAction.addWidget(self.failure_page)
        self.horizontalLayout_2.addWidget(self.statusAction)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.statusAction.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Item Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Publish path:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setStatusTip(QtGui.QApplication.translate("Form", "Enable item to be published", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
