# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_form.ui'
#
# Created: Thu Apr 06 00:04:34 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(665, 404)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon_256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loading_page = QtGui.QWidget()
        self.loading_page.setObjectName("loading_page")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.loading_page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem = QtGui.QSpacerItem(20, 93, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_11 = QtGui.QLabel(self.loading_page)
        self.label_11.setMinimumSize(QtCore.QSize(128, 128))
        self.label_11.setMaximumSize(QtCore.QSize(128, 128))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/img/blue_circle.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.label_12 = QtGui.QLabel(self.loading_page)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        spacerItem3 = QtGui.QSpacerItem(20, 92, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.loading_page)
        self.items_page = QtGui.QWidget()
        self.items_page.setObjectName("items_page")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.items_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtGui.QScrollArea(self.items_page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 441, 366))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.items_page)
        self.progress_page = QtGui.QWidget()
        self.progress_page.setObjectName("progress_page")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.progress_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.label = QtGui.QLabel(self.progress_page)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.progressBar = QtGui.QProgressBar(self.progress_page)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.statusMessage = QtGui.QLabel(self.progress_page)
        self.statusMessage.setObjectName("statusMessage")
        self.verticalLayout_6.addWidget(self.statusMessage)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.progress_page)
        self.errors_page = QtGui.QWidget()
        self.errors_page.setObjectName("errors_page")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.errors_page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtGui.QLabel(self.errors_page)
        self.label_8.setMinimumSize(QtCore.QSize(80, 80))
        self.label_8.setMaximumSize(QtCore.QSize(80, 80))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/img/semaphore.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.label_2 = QtGui.QLabel(self.errors_page)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.errors_page)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.scrollAreaErrors = QtGui.QScrollArea(self.errors_page)
        self.scrollAreaErrors.setMinimumSize(QtCore.QSize(0, 280))
        self.scrollAreaErrors.setWidgetResizable(True)
        self.scrollAreaErrors.setObjectName("scrollAreaErrors")
        self.scrollAreaWidgetContentsErrors = QtGui.QWidget()
        self.scrollAreaWidgetContentsErrors.setGeometry(QtCore.QRect(0, 0, 441, 278))
        self.scrollAreaWidgetContentsErrors.setObjectName("scrollAreaWidgetContentsErrors")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.scrollAreaWidgetContentsErrors)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollAreaErrors.setWidget(self.scrollAreaWidgetContentsErrors)
        self.verticalLayout_8.addWidget(self.scrollAreaErrors)
        self.stackedWidget.addWidget(self.errors_page)
        self.success_page = QtGui.QWidget()
        self.success_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.success_page.setObjectName("success_page")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.success_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_10 = QtGui.QLabel(self.success_page)
        self.label_10.setMinimumSize(QtCore.QSize(128, 128))
        self.label_10.setMaximumSize(QtCore.QSize(128, 128))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/img/success.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.label_9 = QtGui.QLabel(self.success_page)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.stackedWidget.addWidget(self.success_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.frame = QtGui.QFrame(Form)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkbox_publish_ones = QtGui.QCheckBox(self.groupBox_2)
        self.checkbox_publish_ones.setEnabled(False)
        self.checkbox_publish_ones.setChecked(False)
        self.checkbox_publish_ones.setObjectName("checkbox_publish_ones")
        self.verticalLayout_3.addWidget(self.checkbox_publish_ones)
        self.checkbox_unpublish_ones = QtGui.QCheckBox(self.groupBox_2)
        self.checkbox_unpublish_ones.setEnabled(False)
        self.checkbox_unpublish_ones.setChecked(True)
        self.checkbox_unpublish_ones.setObjectName("checkbox_unpublish_ones")
        self.verticalLayout_3.addWidget(self.checkbox_unpublish_ones)
        self.button_select_unpublished = QtGui.QPushButton(self.groupBox_2)
        self.button_select_unpublished.setEnabled(False)
        self.button_select_unpublished.setObjectName("button_select_unpublished")
        self.verticalLayout_3.addWidget(self.button_select_unpublished)
        self.button_publish_selected = QtGui.QPushButton(self.groupBox_2)
        self.button_publish_selected.setEnabled(False)
        self.button_publish_selected.setObjectName("button_publish_selected")
        self.verticalLayout_3.addWidget(self.button_publish_selected)
        self.button_publish_al = QtGui.QPushButton(self.groupBox_2)
        self.button_publish_al.setEnabled(False)
        self.button_publish_al.setObjectName("button_publish_al")
        self.verticalLayout_3.addWidget(self.button_publish_al)
        self.button_publish_rescan = QtGui.QPushButton(self.groupBox_2)
        self.button_publish_rescan.setEnabled(False)
        self.button_publish_rescan.setObjectName("button_publish_rescan")
        self.verticalLayout_3.addWidget(self.button_publish_rescan)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Dependencies Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Loading scene items...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Publishing", None, QtGui.QApplication.UnicodeUTF8))
        self.statusMessage.setText(QtGui.QApplication.translate("Form", "Publish status...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Some errors reported.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Down you can see a list of the succesfuly and failed published items.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "All items published succesfully!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Context", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Entity: 0020", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Task: EnvironmentFX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Step: EnvironmentFX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Version: 004", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_publish_ones.setText(QtGui.QApplication.translate("Form", "Show Published Items", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_unpublish_ones.setText(QtGui.QApplication.translate("Form", "Show Unpublished Items", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_unpublished.setText(QtGui.QApplication.translate("Form", "Select all Unpublished", None, QtGui.QApplication.UnicodeUTF8))
        self.button_publish_selected.setText(QtGui.QApplication.translate("Form", "Publish Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.button_publish_al.setText(QtGui.QApplication.translate("Form", "Publish All", None, QtGui.QApplication.UnicodeUTF8))
        self.button_publish_rescan.setText(QtGui.QApplication.translate("Form", "Rescan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Dev: Hasiel Alvarez", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
